# Main rules that you, the user, calls from the commandline

configfile: "config/config.yaml"

include: "rules/panel_prep.smk"
include: "rules/sample_processing_main.smk"
include: "rules/snv_assist.smk"
include: "rules/mod_assist.smk"
include: "rules/immune_assist.smk"

SAMPLE = config['sample']
cores = config.get("max_cores", 16)  # Default to 16 if not set


rule get_input_for_minknow:
    input:
        "minknow_input/targets.minknow.bed"


rule run_sample_panel_for_BM_classifier:
    input:
        f"results/{SAMPLE}/{SAMPLE}.panel_results.csv"


rule test_things:
    # snakemake --dag test_things | dot -Tsvg > dag.test_things.svg
    # snakemake test_things --use-conda
    input:
        panel_results = f"results/{SAMPLE}/{SAMPLE}.panel_results.csv"

