project_name: "BCG_on_NMIBC"
sample: "test6"
panel_metadata: "config/panel_metadata.example.csv"
bam_pass_directory: "/external/data/lucy/20241107-BiomarkerProject/merged_bams"

buffersize_bp: 2000
min_genome_coverage: 0.5
max_genome_coverage: 2.0
max_cores: 16

nextflow:
  profile: "standard"
  threads: 16

# To Run
# mamba activate snakemake
# snakemake get_input_for_minknow --use-conda
# snakemake run_sample_panel_for_BM_classifier --use-conda
# snakemake get_report_for_sample --use-conda

